# Generated by Django 3.0.7 on 2020-06-17 12:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('links', '0002_auto_20200617_1205'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='link',
            name='anon',
        ),
    ]
